spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: root

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supportedCurrencies: USD,EUR,GBP

paymentGateway: stripe

mail:
  host: https://smtp.gmail.com
  port: 5791

communication:
  preference: sms
